name: CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib curl zip unzip gzip
          sudo apt-get install -y build-essential libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev libboost-filesystem-dev
          sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          sudo gzip /usr/local/bin/ninja.gz
          sudo chmod a+x /usr/local/bin/ninja
      
      - name: Setup torch
        run: |
          curl https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip --create-dirs -o ./lib/torch.zip
          unzip ${{github.workspace}}/lib/torch.zip
          rm -rf ${{github.workspace}}/lib/torch.zip
      
      - name: Create build folder
        run: mkdir build

      - name: Configure cmake
        working-directory: ./build
        run: cmake -DCMAKE_PREFIX_PATH=../lib/libtorch/share/cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -Wno-dev

      - name: Create Artifact
        run: |
          mkdir release
          cp build/libtorch-probe.so release/libtorch-probe.so
          cp build/libtorch-probe.so.1 release/libtorch-probe.so.1
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: torch-probe release
          path: release
